version: '2'
services:
  web:
    build: ./
    ports:
      - "3000:3000"
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=3000'
      - 'TZ=America/Sao_Paulo'
    command: flask run --host=0.0.0.0 --port=3000
    volumes:
      - ./src:/src
      - /etc/localtime:/etc/localtime:ro
